### PR TITLE
Converted package to Async package

### LINKED ISSUE #7: Convert extension to AsyncPackage
Synchronous packages are now deprecated in VS2019. Conversion is not really complicated and should be relatively straight forward.
Just follow the instructions on the following page:
https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background?view=vs-2019

Thanks

### PR DESCRIPTION
**Pull request by jspelletier**
Hi,
I converted the package to async package. I've tested in VS2017 + VS2019 and it works.

Fixed #7 

Note: The package doesn't load in VS2015. I am not totally sure why but it might be caused by the following two assemblies:
Microsoft.VisualStudio.Threading
Microsoft.VisualStudio.Shell.Framework

I tried to remove them but got build errors...  Still sending the MR as I don't use VS2015 anymore and don't want to waste more time on this.
Thanks

### CODE REVIEW

**Comment by thennequin** [comment]
Thanks for your pull request.
I can't totally evaluate your pull request for now, because of my dead computer (see Issue #7).
I will continue to work on my working copy, because I think some part of your PR can be skipped and I'm not an expert about the PR, but I will look what you do and see if I can take some part of your code (I see GetAsyncPackage in Common.cs for example).

So I hope you're not hurried, because I think I will work on it again in almost two months.

I saw you change the number version to 0.7.1, but the last number is for build revision.
And I will prefer to make the change of the version number and it will become the 0.8 because of dropping of old Visual Studio version.

**Comment by jspelletier** [comment]
Hi,
I've put 0.7.1 as a temporary version number to avoid interferring with official version numbers. Thus when you will release 0.8 I will be able to upgrade easily. 

I've started using this custom version and sent it to some coworkers that might be interested.

I'm also in vacation for the next month, so no worries!

Thanks

**Comment by thennequin** [comment]
Ok and have you seen some performance improvement with the async package?

**Comment by jspelletier** [comment]
not sure... I haven't used it enough before the change to notice. Anyways, the change to async package is mandatory so there is not much choices...

**Comment by thennequin** [comment]
After many years, I finally create a new branch inspired by your pull request, fixed some things and added support for VS 2022.

**Pull request closed without merging**
